In [79]:
# import numpy as np
# from numpy import random

# x = random.randint(9,size=(9,9))

# arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
# arr2 = np.array([[[1,2],[3,4],[5,6],[7,8]]])

# for i in range(1):
#     for j in range(4):
#         print("0"*(4-j-1),end="")
#         for x in range(2):           
#             print(arr2[i,j,x],end="")
#         print()

# for i in range(3):
#     for j in range(3):
#         print(arr1[i,j])

00012
0034
056
78

In [20]:
import pandas as pd
import numpy as np

# ls = np.array([1,2,3,4,5,6,7,8,9])

# set = {"Day1":[1,31,41],"Day2":[1,31,41],"Day3":[1,31,41],"Day4":[1,31,41],"Day5":[1,31,41]}

# # df = pd.Series(ls,index=["A","B","C","D","E","F","G","H","I"])
# df = pd.DataFrame(set)

# print(df)

   Day1  Day2  Day3  Day4  Day5
0     1     2     3     4     5
1    31     2     3     4     5
2    41     2     3     4     5

In [55]:
import pandas as pd
import numpy as np

# cvs = pd.read_csv("data.csv")


# list11 = []
# list12 = []
# num1 = []
# for i in range(len(cvs)):
#     list11.append(cvs["Duration"].loc[i])

# for i in range(len(cvs)):
#     if cvs["Duration"].loc[i] == min(list11):
#         list12.append(cvs.loc[i])

# for i in range(len(list12)):
#     num1.append(i)

# list12 = pd.DataFrame(list12, index=num1)



# list21 = []
# list22 = []
# num2 = []
# for i in range(len(cvs)):
#     list21.append(cvs["Pulse"].loc[i])

# for i in range(len(cvs)):
#     if cvs["Pulse"].loc[i] == min(list21):
#         list22.append(cvs.loc[i])

# for i in range(len(list22)):
#     num2.append(i)

# list22 = pd.DataFrame(list22,index=num2)


        
# list31 = []
# list32 = []
# num3 = []
# for i in range(len(cvs)):
#     list31.append(cvs["Maxpulse"].loc[i])

# for i in range(len(cvs)):
#     if cvs["Maxpulse"].loc[i] == min(list31):
#         list32.append(cvs.loc[i])

# for i in range(len(list32)):
#     num3.append(i)

# list32 = pd.DataFrame(list32,index=num3)



# list41 = []
# list42 = []
# num4 = []
# for i in range(len(cvs)):
#     list41.append(cvs["Calories"].loc[i])

# for i in range(len(cvs)):
#     if cvs["Calories"].loc[i] == min(list41):
#         list42.append(cvs.loc[i])

# for i in range(len(list42)):
#     num4.append(i)

# list42 = pd.DataFrame(list42,index=num4)

# list12
# list12
# list32
# # list42

In [56]:
# list = []
# for i in range(len(cvs)):
#     if cvs["Duration"].loc[i] >120:
#         cvs["Duration"].loc[i] = 120
#         list.append(cvs.loc[i])
#     else:
#         list.append(cvs.loc[i])

# list = pd.DataFrame(list)
# print(list.to_string())

In [24]:
# list1 = []
# list2 = []
# list3 = []
# num1 = []
# num2 = []
# num3 = []


# for i in range(len(cvs)):
#     if cvs["Duration"].loc[i] >=15 and cvs["Duration"].loc[i] <= 25:
#         list1.append(cvs.loc[i])
#     elif cvs["Duration"].loc[i] >= 35 and cvs["Duration"].loc[i] <= 60:
#         list2.append(cvs.loc[i])
#     elif cvs["Duration"].loc[i] >= 75 and cvs["Duration"].loc[i] <= 300:
#         list3.append(cvs.loc[i])

# for i in range(len(list1)):
#     num1.append(i)
# for i in range(len(list2)):
#     num2.append(i)
# for i in range(len(list3)):
#     num3.append(i)

# list1 = pd.DataFrame(list1,index=num1)
# list3 = pd.DataFrame(list3,index=num3)
# list2 = pd.DataFrame(list2,index=num2)

# # list1
# list2
# # list3

     Duration  Pulse  Maxpulse  Calories
0        60.0  110.0     130.0     409.1
1        60.0  117.0     145.0     479.0
2        60.0  103.0     135.0     340.0
3        45.0  109.0     175.0     282.4
4        45.0  117.0     148.0     406.0
..        ...    ...       ...       ...
109      45.0   95.0     130.0     270.0
110      45.0  100.0     140.0     280.9
111      60.0  105.0     140.0     290.8
112      60.0  110.0     145.0     300.0
113      60.0  115.0     145.0     310.2

[114 rows x 4 columns]

In [26]:
# sumMaxpulse = []
# sumPulse = []
# for i in range(len(cvs)):
#     sumMaxpulse.append(cvs["Maxpulse"].loc[i])
#     sumPulse.append(cvs["Pulse"].loc[i])

# sumMaxpulses = sum(sumMaxpulse)
# sumPulses = sum(sumPulse)
# Xbar1 = sumMaxpulses / int(len(cvs["Maxpulse"]))
# Xbar2 = sumPulses / int(len(cvs["Pulse"]))

# print("Average of Maxpulse = ",Xbar1)
# print("Average of Pulse = ",Xbar2)

Average of Maxpulse =  134.0473372781065
Average of Pulse =  107.46153846153847

In [54]:
import numpy as np
import pandas as pd


df = pd.read_csv("data2.csv")

# new_df = df.dropna(inplace= True)
# df.fillna("Hello",inplace=True)
# df

In [18]:
# x = df["Calories"].mode()
# print(x)

0    300.0
dtype: float64

In [57]:
# df["Date"] = pd.to_datetime(df["Date"])

# df.loc[0,"Duration"] = 60

# df

    Duration          Date  Pulse  Maxpulse Calories
0         60  '2020/12/01'  110.0       130    409.1
1         60  '2020/12/02'  117.0       145    479.0
2         60  '2020/12/03'  103.0       135    340.0
3         20  '2020/12/04'  109.0       175    282.4
4         20  '2020/12/05'  117.0       148    406.0
5         60  '2020/12/06'  102.0       127    300.0
6         60  '2020/12/07'  110.0       136    374.0
7         20  '2020/12/08'  104.0       134    253.3
8         20  '2020/12/09'  109.0       133    195.1
9         60  '2020/12/10'   98.0       124    269.0
10        60  '2020/12/11'  103.0       147    329.3
11        60  '2020/12/12'  100.0       120    250.7
12        60  '2020/12/12'  100.0       120    250.7
13        60  '2020/12/13'  106.0       128    345.3
14        60  '2020/12/14'  104.0       132    379.3
15        60  '2020/12/15'   98.0       123    275.0
16        60  '2020/12/16'   98.0       120    215.2
17        60  '2020/12/17'  100.0       120    300.0
18        20  '2020/12/18'   90.0       112     à¸§à¹ˆà¸²à¸‡
19        60  '2020/12/19'  103.0       123    323.0
20        20  '2020/12/20'   97.0       125    243.0
21        60  '2020/12/21'  108.0       131    364.2
22        20          à¸§à¹ˆà¸²à¸‡  100.0       119    282.0
23        60  '2020/12/23'  130.0       101    300.0
24        20  '2020/12/24'  105.0       132    246.0
25        60  '2020/12/25'  102.0       126    334.5
26        60      20201226  100.0       120    250.0
27        60  '2020/12/27'   92.0       118    241.0
28        60  '2020/12/28'  103.0       132     à¸§à¹ˆà¸²à¸‡
29        60  '2020/12/29'  100.0       132    280.0
30        60  '2020/12/30'  102.0       129    380.3
31        60  '2020/12/31'   92.0       115    243.0

In [84]:
list = []
for i in range(len(df)):
    if df["Duration"].loc[i] > 60:
        df["Duration"].loc[i] = 20


for i in range(len(df)):
    df["Pulse"] = df["Pulse"].astype(float)

for i in range(len(df)):
    df.fillna("à¸§à¹ˆà¸²à¸‡",inplace=True)

df

    Duration          Date  Pulse  Maxpulse Calories
0         60  '2020/12/01'  110.0       130    409.1
1         60  '2020/12/02'  117.0       145    479.0
2         60  '2020/12/03'  103.0       135    340.0
3         20  '2020/12/04'  109.0       175    282.4
4         20  '2020/12/05'  117.0       148    406.0
5         60  '2020/12/06'  102.0       127    300.0
6         60  '2020/12/07'  110.0       136    374.0
7         20  '2020/12/08'  104.0       134    253.3
8         20  '2020/12/09'  109.0       133    195.1
9         60  '2020/12/10'   98.0       124    269.0
10        60  '2020/12/11'  103.0       147    329.3
11        60  '2020/12/12'  100.0       120    250.7
12        60  '2020/12/12'  100.0       120    250.7
13        60  '2020/12/13'  106.0       128    345.3
14        60  '2020/12/14'  104.0       132    379.3
15        60  '2020/12/15'   98.0       123    275.0
16        60  '2020/12/16'   98.0       120    215.2
17        60  '2020/12/17'  100.0       120    300.0
18        20  '2020/12/18'   90.0       112     à¸§à¹ˆà¸²à¸‡
19        60  '2020/12/19'  103.0       123    323.0
20        20  '2020/12/20'   97.0       125    243.0
21        60  '2020/12/21'  108.0       131    364.2
22        20          à¸§à¹ˆà¸²à¸‡  100.0       119    282.0
23        60  '2020/12/23'  130.0       101    300.0
24        20  '2020/12/24'  105.0       132    246.0
25        60  '2020/12/25'  102.0       126    334.5
26        60      20201226  100.0       120    250.0
27        60  '2020/12/27'   92.0       118    241.0
28        60  '2020/12/28'  103.0       132     à¸§à¹ˆà¸²à¸‡
29        60  '2020/12/29'  100.0       132    280.0
30        60  '2020/12/30'  102.0       129    380.3
31        60  '2020/12/31'   92.0       115    243.0